In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute  import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
x_train

    age  gender  fever   cough       city
3    31  Female   98.0    Mild    Kolkata
78   11    Male  100.0    Mild  Bangalore
46   19  Female  101.0    Mild     Mumbai
26   19  Female  100.0    Mild    Kolkata
99   10  Female   98.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
70   68  Female  101.0  Strong      Delhi
80   14  Female   99.0    Mild     Mumbai
67   65    Male   99.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata
92   82  Female  102.0  Strong    Kolkata

[80 rows x 5 columns]

In [7]:
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [8]:
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [9]:
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

(80, 4)

In [10]:
x_train_age = x_train.drop(columns = ['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns = ['gender','fever','cough','city']).values
x_train_age.shape

(80, 1)

In [11]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [12]:
x_train_transformed.shape

(80, 7)

## Column Transformer

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [15]:
transformer.fit_transform(x_train).shape

(80, 7)

In [16]:
transformer.transform(x_test).shape

(20, 7)